DROP TABLE IF EXISTS compilations_events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
  id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  varchar(250) NOT NULL,
  email varchar(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories (
  id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
  id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar,
  annotation varchar,
  category_id bigint REFERENCES categories (id),
  paid boolean,
  event_date timestamp,
  user_id bigint REFERENCES users (id) ON DELETE CASCADE,
  description varchar,
  participant_limit int,
  state varchar,
  created_on timestamp,
  published_on timestamp,
  lat float,
  lon float,
  request_moderation boolean,
  confirmed_requests bigint,
  views bigint
);
CREATE TABLE IF NOT EXISTS requests (
  id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES users (id) ON DELETE CASCADE,
  event_id bigint REFERENCES events (id) ON DELETE CASCADE,
  status varchar,
  created timestamp
);
CREATE TABLE IF NOT EXISTS compilations (
  id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar,
  pinned boolean
);
CREATE TABLE IF NOT EXISTS compilations_events (
  compilations_id  bigint,
  events_id bigint,
  CONSTRAINT "PK_compilations_events" PRIMARY KEY (compilations_id, events_id),
  CONSTRAINT "FK_compilation_id" FOREIGN KEY (compilations_id) REFERENCES compilations (id) ON DELETE CASCADE,
  CONSTRAINT "FK_event_id" FOREIGN KEY (events_id) REFERENCES events (id) ON DELETE CASCADE
);
