version: '3.1'
services:
  stats-server:
    build: stat/stats-server
    image: stats-server
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
        - DB_NAME=postgres
        - DB_HOST=stats-db
        - DB_PORT=5432
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres



  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
