version: '3.1'
services:
  stats-server:
    build: stat/stats-server
    image: stats-server
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
        - DB_NAME=postgres
        - DB_HOST=stats-db
        - DB_PORT=5432
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  stats-db:
    image: postgres:14-alpine
    build:
      context: stat/stats-server/
      dockerfile: Dockerfile.postgres
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgresStat
      - POSTGRES_HOST_AUTH_METHOD=trust



  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm_service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SERVER_URL=http://server:9090


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgresService