version: '3.1'
services:
  stats-server:
    build: stat/stats-server
    image: stats-server
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
  stats-db:
    image: postgres:14-alpine
    build:
      context: stat/stats-server/
      dockerfile: Dockerfile.postgres
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=stats
      - POSTGRES_HOST_AUTH_METHOD=trust



  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm_service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - CLIENT_URL=http://localhost:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root



  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust